name: Makefile CI

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build
      run: make all
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.3.3
      with:
        name: Fedora Zip
        path: Fedora40.zip

    - name: Clean Up
      run: make clean
